# Military Power Clustering Project
-World military power
Source : globalfirepower.com on 1st may 2020

- https://data.world/vizzup/world-military-power/workspace/file?filename=World+military+power.xlsx

# Import Libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('max_columns',100)
pd.set_option('max_rows',900)
pd.set_option('max_colwidth',200)

# Ingest Data

In [6]:
data = pd.read_excel("World military power.xlsx",header = 1)
data.head()

,Military Strength,Military Strength Power Index,Aircraft Strength,Aircraft Strength value,Fighter/Interceptor Strength,Fighter/Interceptor Strength value,Attack Aircraft Strength,Attack Aircraft Strength value,Transport Aircraft Fleet Strength,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet,Trainer Aircraft Fleet value,Helicopter Fleet Strength,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength,Attack Helicopter Fleet Strength value,Tank Strength,Tank Strength value,AFV/APC Strength,AFV/APC Strength value,Self-Propelled Artillery Strength,Self-Propelled Artillery Strength value,Towed Artillery Strength,Towed Artillery Strength value,Rocket Projector Strength,Rocket Projector Strength value,Navy Fleet Strengths,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength,Submarine Fleet Strength value,Destroyer Fleet Strength,Destroyer Fleet Strength value,Frigate Fleet Strength,Frigate Fleet Strength value,defense spending budget,defense spending budget value,External Debt,External Debt value,Airport Totals,Airport Totals value,Oil Production,Oil Production value,Oil Consumption,Oil Consumption value,Proven Oil Reserves,Proven Oil Reserves value,Available Manpower,Available Manpower value,Total Population,Total Population value,Total Square Land Area,Total Square Land Area value,Total Coastline Coverage,Total Coastline Coverage value,Total Waterway Coverage,Total Waterway Coverage value,Total Border Coverage,Total Border Coverage value
0,Afghanistan,1.3444,Afghanistan,260.0,Afghanistan,0.0,Afghanistan,25.0,Afghanistan,30.0,Afghanistan,0.0,Afghanistan,187.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,1062.0,Afghanistan,0.0,Afghanistan,176.0,Afghanistan,50.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,"12,00,00,00,000",Afghanistan,"2,84,00,00,000",Afghanistan,43.0,Afghanistan,0.0,Afghanistan,5500.0,Afghanistan,0.0,Afghanistan,"1,43,25,743",Afghanistan,"3,49,40,837",Afghanistan,"6,52,230",Afghanistan,0.0,Afghanistan,1200.0,Afghanistan,5987.0
1,Albania,2.3137,Albania,19.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,19.0,Albania,0.0,Albania,0.0,Albania,467.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,38.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,"25,00,00,000",Albania,"9,50,50,00,000",Albania,4.0,Albania,16000.0,Albania,42500.0,Albania,"16,83,00,000",Albania,"15,19,438",Albania,"30,57,220",Albania,28748.0,Albania,362.0,Albania,41.0,Albania,691.0
2,Algeria,0.4659,Algeria,551.0,Algeria,103.0,Algeria,22.0,Algeria,59.0,Algeria,87.0,Algeria,257.0,Algeria,45.0,Algeria,880.0,Algeria,7361.0,Algeria,320.0,Algeria,240.0,Algeria,316.0,Algeria,201.0,Algeria,0.0,Algeria,6.0,Algeria,0.0,Algeria,5.0,Algeria,"13,00,00,00,000",Algeria,"6,26,00,00,000",Algeria,157.0,Algeria,"13,06,000",Algeria,"3,25,000",Algeria,"12,20,00,00,000",Algeria,"2,07,41,263",Algeria,"4,16,57,488",Algeria,"23,81,741",Algeria,998.0,Algeria,0.0,Algeria,6734.0
3,Angola,0.8379,Angola,295.0,Angola,72.0,Angola,18.0,Angola,30.0,Angola,47.0,Angola,126.0,Angola,15.0,Angola,379.0,Angola,595.0,Angola,28.0,Angola,357.0,Angola,115.0,Angola,57.0,Angola,0.0,Angola,0.0,Angola,0.0,Angola,0.0,Angola,"7,00,00,00,000",Angola,"42,08,00,00,000",Angola,176.0,Angola,"16,66,000",Angola,82300.0,Angola,"8,27,30,00,000",Angola,"62,44,205",Angola,"3,03,55,880",Angola,"12,46,700",Angola,1600.0,Angola,1300.0,Angola,5369.0
4,Argentina,0.6521,Argentina,227.0,Argentina,24.0,Argentina,7.0,Argentina,9.0,Argentina,64.0,Argentina,100.0,Argentina,0.0,Argentina,370.0,Argentina,739.0,Argentina,83.0,Argentina,172.0,Argentina,26.0,Argentina,49.0,Argentina,0.0,Argentina,2.0,Argentina,4.0,Argentina,0.0,Argentina,"4,20,00,00,000",Argentina,"2,14,90,00,00,000",Argentina,1138.0,Argentina,"4,79,400",Argentina,"6,85,000",Argentina,"2,18,50,00,000",Argentina,"2,01,79,430",Argentina,"4,46,94,198",Argentina,"27,80,400",Argentina,4989.0,Argentina,11000.0,Argentina,11968.0

# EDA

In [7]:
df = data.copy()

In [8]:
df.head()

,Military Strength,Military Strength Power Index,Aircraft Strength,Aircraft Strength value,Fighter/Interceptor Strength,Fighter/Interceptor Strength value,Attack Aircraft Strength,Attack Aircraft Strength value,Transport Aircraft Fleet Strength,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet,Trainer Aircraft Fleet value,Helicopter Fleet Strength,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength,Attack Helicopter Fleet Strength value,Tank Strength,Tank Strength value,AFV/APC Strength,AFV/APC Strength value,Self-Propelled Artillery Strength,Self-Propelled Artillery Strength value,Towed Artillery Strength,Towed Artillery Strength value,Rocket Projector Strength,Rocket Projector Strength value,Navy Fleet Strengths,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength,Submarine Fleet Strength value,Destroyer Fleet Strength,Destroyer Fleet Strength value,Frigate Fleet Strength,Frigate Fleet Strength value,defense spending budget,defense spending budget value,External Debt,External Debt value,Airport Totals,Airport Totals value,Oil Production,Oil Production value,Oil Consumption,Oil Consumption value,Proven Oil Reserves,Proven Oil Reserves value,Available Manpower,Available Manpower value,Total Population,Total Population value,Total Square Land Area,Total Square Land Area value,Total Coastline Coverage,Total Coastline Coverage value,Total Waterway Coverage,Total Waterway Coverage value,Total Border Coverage,Total Border Coverage value
0,Afghanistan,1.3444,Afghanistan,260.0,Afghanistan,0.0,Afghanistan,25.0,Afghanistan,30.0,Afghanistan,0.0,Afghanistan,187.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,1062.0,Afghanistan,0.0,Afghanistan,176.0,Afghanistan,50.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,"12,00,00,00,000",Afghanistan,"2,84,00,00,000",Afghanistan,43.0,Afghanistan,0.0,Afghanistan,5500.0,Afghanistan,0.0,Afghanistan,"1,43,25,743",Afghanistan,"3,49,40,837",Afghanistan,"6,52,230",Afghanistan,0.0,Afghanistan,1200.0,Afghanistan,5987.0
1,Albania,2.3137,Albania,19.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,19.0,Albania,0.0,Albania,0.0,Albania,467.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,38.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,"25,00,00,000",Albania,"9,50,50,00,000",Albania,4.0,Albania,16000.0,Albania,42500.0,Albania,"16,83,00,000",Albania,"15,19,438",Albania,"30,57,220",Albania,28748.0,Albania,362.0,Albania,41.0,Albania,691.0
2,Algeria,0.4659,Algeria,551.0,Algeria,103.0,Algeria,22.0,Algeria,59.0,Algeria,87.0,Algeria,257.0,Algeria,45.0,Algeria,880.0,Algeria,7361.0,Algeria,320.0,Algeria,240.0,Algeria,316.0,Algeria,201.0,Algeria,0.0,Algeria,6.0,Algeria,0.0,Algeria,5.0,Algeria,"13,00,00,00,000",Algeria,"6,26,00,00,000",Algeria,157.0,Algeria,"13,06,000",Algeria,"3,25,000",Algeria,"12,20,00,00,000",Algeria,"2,07,41,263",Algeria,"4,16,57,488",Algeria,"23,81,741",Algeria,998.0,Algeria,0.0,Algeria,6734.0
3,Angola,0.8379,Angola,295.0,Angola,72.0,Angola,18.0,Angola,30.0,Angola,47.0,Angola,126.0,Angola,15.0,Angola,379.0,Angola,595.0,Angola,28.0,Angola,357.0,Angola,115.0,Angola,57.0,Angola,0.0,Angola,0.0,Angola,0.0,Angola,0.0,Angola,"7,00,00,00,000",Angola,"42,08,00,00,000",Angola,176.0,Angola,"16,66,000",Angola,82300.0,Angola,"8,27,30,00,000",Angola,"62,44,205",Angola,"3,03,55,880",Angola,"12,46,700",Angola,1600.0,Angola,1300.0,Angola,5369.0
4,Argentina,0.6521,Argentina,227.0,Argentina,24.0,Argentina,7.0,Argentina,9.0,Argentina,64.0,Argentina,100.0,Argentina,0.0,Argentina,370.0,Argentina,739.0,Argentina,83.0,Argentina,172.0,Argentina,26.0,Argentina,49.0,Argentina,0.0,Argentina,2.0,Argentina,4.0,Argentina,0.0,Argentina,"4,20,00,00,000",Argentina,"2,14,90,00,00,000",Argentina,1138.0,Argentina,"4,79,400",Argentina,"6,85,000",Argentina,"2,18,50,00,000",Argentina,"2,01,79,430",Argentina,"4,46,94,198",Argentina,"27,80,400",Argentina,4989.0,Argentina,11000.0,Argentina,11968.0

In [11]:
df

,Military Strength,Military Strength Power Index,Aircraft Strength,Aircraft Strength value,Fighter/Interceptor Strength,Fighter/Interceptor Strength value,Attack Aircraft Strength,Attack Aircraft Strength value,Transport Aircraft Fleet Strength,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet,Trainer Aircraft Fleet value,Helicopter Fleet Strength,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength,Attack Helicopter Fleet Strength value,Tank Strength,Tank Strength value,AFV/APC Strength,AFV/APC Strength value,Self-Propelled Artillery Strength,Self-Propelled Artillery Strength value,Towed Artillery Strength,Towed Artillery Strength value,Rocket Projector Strength,Rocket Projector Strength value,Navy Fleet Strengths,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength,Submarine Fleet Strength value,Destroyer Fleet Strength,Destroyer Fleet Strength value,Frigate Fleet Strength,Frigate Fleet Strength value,defense spending budget,defense spending budget value,External Debt,External Debt value,Airport Totals,Airport Totals value,Oil Production,Oil Production value,Oil Consumption,Oil Consumption value,Proven Oil Reserves,Proven Oil Reserves value,Available Manpower,Available Manpower value,Total Population,Total Population value,Total Square Land Area,Total Square Land Area value,Total Coastline Coverage,Total Coastline Coverage value,Total Waterway Coverage,Total Waterway Coverage value,Total Border Coverage,Total Border Coverage value
0,Afghanistan,1.3444,Afghanistan,260.0,Afghanistan,0.0,Afghanistan,25.0,Afghanistan,30.0,Afghanistan,0.0,Afghanistan,187.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,1062.0,Afghanistan,0.0,Afghanistan,176.0,Afghanistan,50.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,0.0,Afghanistan,"12,00,00,00,000",Afghanistan,"2,84,00,00,000",Afghanistan,43.0,Afghanistan,0.0,Afghanistan,5500.0,Afghanistan,0.0,Afghanistan,"1,43,25,743",Afghanistan,"3,49,40,837",Afghanistan,"6,52,230",Afghanistan,0.0,Afghanistan,1200.0,Afghanistan,5987.0
1,Albania,2.3137,Albania,19.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,19.0,Albania,0.0,Albania,0.0,Albania,467.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,38.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,0.0,Albania,"25,00,00,000",Albania,"9,50,50,00,000",Albania,4.0,Albania,16000.0,Albania,42500.0,Albania,"16,83,00,000",Albania,"15,19,438",Albania,"30,57,220",Albania,28748.0,Albania,362.0,Albania,41.0,Albania,691.0
2,Algeria,0.4659,Algeria,551.0,Algeria,103.0,Algeria,22.0,Algeria,59.0,Algeria,87.0,Algeria,257.0,Algeria,45.0,Algeria,880.0,Algeria,7361.0,Algeria,320.0,Algeria,240.0,Algeria,316.0,Algeria,201.0,Algeria,0.0,Algeria,6.0,Algeria,0.0,Algeria,5.0,Algeria,"13,00,00,00,000",Algeria,"6,26,00,00,000",Algeria,157.0,Algeria,"13,06,000",Algeria,"3,25,000",Algeria,"12,20,00,00,000",Algeria,"2,07,41,263",Algeria,"4,16,57,488",Algeria,"23,81,741",Algeria,998.0,Algeria,0.0,Algeria,6734.0
3,Angola,0.8379,Angola,295.0,Angola,72.0,Angola,18.0,Angola,30.0,Angola,47.0,Angola,126.0,Angola,15.0,Angola,379.0,Angola,595.0,Angola,28.0,Angola,357.0,Angola,115.0,Angola,57.0,Angola,0.0,Angola,0.0,Angola,0.0,Angola,0.0,Angola,"7,00,00,00,000",Angola,"42,08,00,00,000",Angola,176.0,Angola,"16,66,000",Angola,82300.0,Angola,"8,27,30,00,000",Angola,"62,44,205",Angola,"3,03,55,880",Angola,"12,46,700",Angola,1600.0,Angola,1300.0,Angola,5369.0
4,Argentina,0.6521,Argentina,227.0,Argentina,24.0,Argentina,7.0,Argentina,9.0,Argentina,64.0,Argentina,100.0,Argentina,0.0,Argentina,370.0,Argentina,739.0,Argentina,83.0,Argentina,172.0,Argentina,26.0,Argentina,49.0,Argentina,0.0,Argentina,2.0,Argentina,4.0,Argentina,0.0,Argentina,"4,20,00,00,000",Argentina,"2,14,90,00,00,000",Argentina,1138.0,Argentina,"4,79,400",Argentina,"6,85,000",Argentina,"2,18,50,00,000",Argentina,"2,01,79,430",Argentina,"4,46,94,198",Argentina,"27,80,400",Argentina,4989.0,Argentina,11000.0,Argentina,11968.0
5,Armenia,2.1251,Armenia,64.0,Armenia,0.0,Armenia,9.0,Armenia,3.0,Armenia,13.0,Armenia,37.0,Armenia,20.0,Armenia,110.0,Armenia,748.0,Armenia,38.0,Armenia,150.0,Armenia,68.0,Armenia,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Armenia,"1,38,50,00,000",Armenia,"10,41,00,00,000",Armenia,11.0,Armenia,0.0,Armenia,47500.0,Armenia,0.0,Armenia,"16,96,085",Armenia,"30,38,217",Armenia,29743.0,NaN,NaN,Armenia,0.0,Armenia,1570.0
6,Australia,0.3225,Australia,464.0,Australia,82.0,Australia,6.0,Australia,38.0,Australia,174.0,Australia,133.0,Australia,22.0,Australia,59.0,Australia,3051.0,Australia,0.0,Australia,54.0,Australia,0.0,Australia,48.0,Australia,2.0,Australia,6.0,Australia,2.0,Australia,8.0,Australia,"26,30,00,00,000",Australia,"17,14,00,00,00,000",Australia,480.0,Australia,"2,63,000",Australia,"10,05,000",Australia,"1,82,10,00,000",Australia,"1,08,08,002",Australia,"2,34,70,145",Australia,"77,41,220",Australia,25760.0,Australia,2000.0,NaN,NaN
7,Austria,0.9568,Austria,120.0,Austria,15.0,Austria,0.0,Austria,11.0,Austria,32.0,Austria,62.0,Austria,0.0,Austria,56.0,Austria,467.0,Austria,33.0,Austria,0.0,Austria,0.0,Austria,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Austria,"3,38,00,00,000",Austria,"6,30,80,00,00,000",Austria,52.0,Austria,14260.0,Austria,"2,15,000",Austria,"4,30,00,000",Austria,"40,17,691",Austria,"87,93,370",Austria,83871.0,NaN,NaN,Austria,0.0,Austria,2524.0
8,Azerbaijan,0.9463,Azerbaijan,147.0,Azerbaijan,17.0,Azerbaijan,12.0,Azerbaijan,1.0,Azerbaijan,29.0,Azerbaijan,88.0,Azerbaijan,17.0,Azerbaijan,570.0,Azerbaijan,1451.0,Azerbaijan,187.0,Azerbaijan,227.0,Azerbaijan,162.0,Azerbaijan,31.0,Azerbaijan,0.0,Azerbaijan,4.0,Azerbaijan,0.0,Azerbaijan,1.0,Azerbaijan,"2,80,50,00,000",Azerbaijan,"17,41,00,00,000",Azerbaijan,37.0,Azerbaijan,"7,89,300",Azerbaijan,"1,80,000",Azerbaijan,"7,00,00,00,000",Azerbaijan,"50,42,346",Azerbaijan,"1,00,46,516",Azerbaijan,86600.0,Azerbaijan,713.0,Azerbaijan,0.0,Azerbaijan,2468.0
9,Bahrain,1.8547,Bahrain,109.0,Bahrain,17.0,Bahrain,0.0,Bahrain,2.0,Bahrain,37.0,Bahrain,65.0,Bahrain,22.0,Bahrain,180.0,Bahrain,843.0,Bahrain,33.0,Bahrain,26.0,Bahrain,17.0,Bahrain,39.0,Bahrain,0.0,Bahrain,0.0,Bahrain,0.0,Bahrain,1.0,Bahrain,"1,41,50,00,000",Bahrain,"52,15,00,00,000",Bahrain,4.0,Bahrain,45000.0,Bahrain,55000.0,Bahrain,"12,46,00,000",Bahrain,"8,06,505",Bahrain,"14,22,659",Bahrain,760.0,Bahrain,161.0,Bahrain,0.0,NaN,NaN
10,Bangladesh,0.7066,Bangladesh,177.0,Bangladesh,44.0,Bangladesh,0.0,Bangladesh,11.0,Bangladesh,57.0,Bangladesh,67.0,Bangladesh,0.0,Bangladesh,276.0,Bangladesh,1230.0,Bangladesh,18.0,Bangladesh,419.0,Bangladesh,72.0,Bangladesh,112.0,Bangladesh,0.0,Bangladesh,2.0,Bangladesh,0.0,Bangladesh,8.0,Bangladesh,"3,80,00,00,000",Bangladesh,"50,26,00,00,000",Bangladesh,18.0,Bangladesh,3666.0,Bangladesh,"1,12,000",Bangladesh,"2,80,00,000",Bangladesh,"7,89,13,289",Bangladesh,"15,94,53,001",Bangladesh,"1,43,998",Bangladesh,580.0,Bangladesh,8370.0,Bangladesh,4413.0
11,Belarus,0.8179,Belarus,202.0,Belarus,39.0,Belarus,68.0,Belarus,4.0,Belarus,28.0,Belarus,63.0,Belarus,21.0,Belarus,532.0,Belarus,1560.0,Belarus,482.0,Belarus,228.0,Belarus,238.0,Belarus,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Belarus,"62,37,02,800",Belarus,"39,92,00,00,000",Belarus,65.0,Belarus,32000.0,Belarus,"1,90,000",Belarus,"19,80,00,000",Belarus,"49,82,905",Belarus,"95,27,543",Belarus,"2,07,600",NaN,NaN,Belarus,2500.0,Belarus,3599.0
12,Belgium,1.0499,Belgium,148.0,Belgium,43.0,Belgium,0.0,Belgium,12.0,Belgium,64.0,Belgium,29.0,Belgium,0.0,Belgium,0.0,Belgium,984.0,Belgium,0.0,Belgium,0.0,Belgium,0.0,Belgium,17.0,Belgium,0.0,Belgium,0.0,Belgium,0.0,Belgium,2.0,Belgium,"4,92,10,00,000",Belgium,"12,81,00,00,00,000",Belgium,41.0,Belgium,0.0,Belgium,"6,45,000",Belgium,0.0,Belgium,"48,33,107",Belgium,"1,15,70,762",Belgium,30528.0,Belgium,67.0,Belgium,2043.0,Belgium,1297.0
13,Bhutan,10.1681,Bhutan,2.0,Bhutan,0.0,Bhutan,0.0,Bhutan,0.0,Bhutan,0.0,Bhutan,2.0,Bhutan,0.0,Bhutan,0.0,Bhutan,27.0,Bhutan,0.0,Bhutan,0.0,Bhutan,0.0,Bhutan,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bhutan,"2,51,20,000",Bhutan,"2,67,10,00,000",Bhutan,2.0,Bhutan,0.0,Bhutan,2000.0,Bhutan,0.0,Bhutan,"1,76,808",Bhutan,"7,66,397",Bhutan,38394.0,NaN,NaN,Bhutan,0.0,Bhutan,1136.0
14,Bolivia,0.9942,Bolivia,69.0,Bolivia,0.0,Bolivia,0.0,Bolivia,14.0,Bolivia,23.0,Bolivia,38.0,Bolivia,0.0,Bolivia,54.0,Bolivia,137.0,Bolivia,0.0,Bolivia,86.0,Bolivia,0.0,Bolivia,173.0,Bolivia,0.0,Bolivia,0.0,Bolivia,0.0,Bolivia,0.0,Bolivia,"66,00,00,000",Bolivia,"12,81,00,00,000",Bolivia,855.0,Bolivia,59330.0,Bolivia,60000.0,Bolivia,"21,15,00,000",Bolivia,"50,75,416",Bolivia,"1,13,06,341",Bolivia,"10,98,581",NaN,NaN,Bolivia,10000.0,Bolivia,7252.0
15,Bosnia and Herzegovina,3.8586,Bosnia and Herzegovina,19.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,19.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,320.0,Bosnia and Herzegovina,332.0,Bosnia and Herzegovina,24.0,Bosnia and Herzegovina,837.0,Bosnia and Herzegovina,143.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,"16,50,00,000",Bosnia and Herzegovina,"10,87,00,00,000",Bosnia and Herzegovina,24.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,32500.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,"23,94,632",Bosnia and Herzegovina,"38,49,891",Bosnia and Herzegovina,51197.0,Bosnia and Herzegovina,20.0,Bosnia and Herzegovina,0.0,Bosnia and Herzegovina,1543.0
16,Botswana,2.0582,Botswana,45.0,Botswana,10.0,Botswana,0.0,Botswana,11.0,Botswana,8.0,Botswana,16.0,Botswana,0.0,Botswana,55.0,Botswana,245.0,Botswana,0.0,Botswana,30.0,Botswana,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Botswana,"45,00,00,000",Botswana,"2,18,70,00,000",Botswana,74.0,Botswana,0.0,Botswana,16500.0,Botswana,0.0,Botswana,"9,62,617",Botswana,"22,49,104",Botswana,"5,81,730",NaN,NaN,Botswana,0.0,Botswana,4347.0
17,Brazil,0.1988,Brazil,715.0,Brazil,43.0,Brazil,78.0,Brazil,126.0,Brazil,198.0,Brazil,242.0,Brazil,12.0,Brazil,437.0,Brazil,1820.0,Brazil,132.0,Brazil,565.0,Brazil,84.0,Brazil,112.0,Brazil,0.0,Brazil,6.0,Brazil,0.0,Brazil,7.0,Brazil,"27,80,00,00,000",Brazil,"5,47,40,00,00,000",Brazil,4093.0,Brazil,"26,22,000",Brazil,"30,20,000",Brazil,"13,00,00,00,000",Brazil,"10,77,64,996",Brazil,"20,88,46,892",Brazil,"85,14,877",Brazil,7491.0,Brazil,50000.0,Brazil,16145.0
18,Bulgaria,0.8916,Bulgaria,63.0,Bulgaria,13.0,Bulgaria,4.0,Bulgaria,5.0,Bulgaria,20.0,Bulgaria,25.0,Bulgaria,2.0,Bulgaria,710.0,Bulgaria,2000.0,Bulgaria,506.0,Bulgaria,350.0,Bulgaria,192.0,Bulgaria,29.0,Bulgaria,0.0,Bulgaria,0.0,Bulgaria,0.0,Bulgaria,4.0,Bulgaria,"1,07,90,00,000",Bulgaria,"42,06,00,00,000",Bulgaria,68.0,Bulgaria,1000.0,Bulgaria,"1,15,000",Bulgaria,"1,50,00,000",Bulgaria,"32,78,916",Bulgaria,"70,57,504",Bulgaria,"1,10,880",Bulgaria,354.0,Bulgaria,470.0,Bulgaria,1806.0
19,Burkina Faso,1.9009,Burkina Faso,16.0,Burkina Faso,0.0,Burkina Faso,3.0,Burkina Faso,1.0,Burkina Faso,4.0,Burkina Faso,8.0,Burkina Faso,2.0,Burkina Faso,0.0,Burkina Faso,350.0,Burkina Faso,0.0,Burkina Faso,0.0,Burkina Faso,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Burkina Faso,"13,00,00,000",Burkina Faso,"3,05,60,00,000",Burkina Faso,23.0,Burkina Faso,0.0,Burkina Faso,10500.0,Burkina Faso,0.0,Burkina Faso,"78,00,000",Burkina Faso,"1,97,42,715",Burkina Faso,"2,74,200",NaN,NaN,Burkina Faso,0.0,Burkina Faso,3611.0
20,Cambodia,2.0557,Cambodia,22.0,Cambodia,0.0,Cambodia,0.0,Cambodia,5.0,Cambodia,0.0,Cambodia,17.0,Cambodia,0.0,Cambodia,263.0,Cambodia,340.0,Cambodia,0.0,Cambodia,150.0,Cambodia,570.0,Cambodia,27.0,Cambodia,0.0,Cambodia,0.0,Cambodia,0.0,Cambodia,0.0,Cambodia,"60,40,00,000",Cambodia,"11,87,00,00,000",Cambodia,16.0,Cambodia,0.0,Cambodia,42500.0,Cambodia,0.0,Cambodia,"81,20,963",Cambodia,"1,64,49,519",Cambodia,"1,81,035",Cambodia,443.0,Cambodia,3700.0,Cambodia,2530.0
21,Cameroon,1.9902,Cameroon,29.0,Cameroon,0.0,Cameroon,0.0,Cameroon,6.0,Cameroon,6.0,Cameroon,15.0,Cameroon,0.0,Cameroon,0.0,Cameroon,222.0,Cameroon,8.0,Cameroon,61.0,Cameroon,20.0,Cameroon,64.0,Cameroon,0.0,Cameroon,0.0,Cameroon,0.0,Cameroon,0.0,Cameroon,"34,70,00,000",Cameroon,"9,37,50,00,000",Cameroon,33.0,Cameroon,75720.0,Cameroon,32500.0,Cameroon,"20,00,00,000",Cameroon,"94,87,157",Cameroon,"2,56,40,965",Cameroon,"4,75,440",Cameroon,400.0,Cameroon,0.0,Cameroon,5018.0
22,Canada,0.3712,Canada,385.0,Canada,62.0,Canada,0.0,Canada,38.0,Canada,135.0,Canada,145.0,Canada,0.0,Canada,80.0,Canada,1973.0,Canada,0.0,Canada,133.0,Canada,0.0,Canada,64.0,Canada,0.0,Canada,4.0,Canada,0.0,Canada,12.0,Canada,"22,50,00,00,000",Canada,"16,08,00,00,00,000",Canada,1467.0,Canada,"39,77,000",Canada,"25,00,000",Canada,"1,69,70,00,00,000",Canada,"1,61,10,865",Canada,"3,58,81,659",Canada,"99,84,670",Canada,"2,02,080",Canada,636.0,Canada,8893.0
23,Central African Republic,3.2889,Central African Republic,3.0,Central African Republic,0.0,Central African Republic,0.0,Central African Republic,2.0,Central African Republic,0.0,Central African Republic,1.0,Central African Republic,0.0,Central African Republic,4.0,Central African Republic,55.0,Central African Republic,0.0,Central African Republic,20.0,Central African Republic,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Central African Republic,"2,00,00,000",Central African Republic,"77,99,00,000",Central African Republic,39.0,Central African Republic,0.0,Central African Republic,4500.0,Central African Republic,0.0,Central African Republic,"23,48,581",Central African Republic,"57,45,062",Central African Republic,"6,22,984",NaN,NaN,Central African Republic,2800.0,Central African Republic,5920.0
24,Chad,1.6383,Chad,35.0,Chad,0.0,Chad,6.0,Chad,6.0,Chad,4.0,Chad,17.0,Chad,3.0,Chad,60.0,Chad,372.0,Chad,10.0,Chad,51.0,Chad,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chad,"20,00,00,000",Chad,"1,72,40,00,000",Chad,59.0,Chad,"1,28,000",Chad,"1,00,000",Chad,"1,50,00,00,000",Chad,"60,30,834",Chad,"1,58,33,116",Chad,"12,84,000",NaN,NaN,Chad,0.0,Chad,6406.0
25,Chile,0.7668,Chile,282.0,Chile,44.0,Chile,0.0,Chile,30.0,Chile,93.0,Chile,92.0,Chile,0.0,Chile,300.0,Chile,1430.0,Chile,48.0,Chile,158.0,Chile,10.0,Chile,69.0,Chile,0.0,Chile,4.0,Chile,0.0,Chile,10.0,Chile,"4,25,00,00,000",Chile,"1,83,40,00,00,000",Chile,481.0,Chile,3244.0,Chile,"3,25,000",Chile,"15,00,00,000",Chile,"86,57,902",Chile,"1,79,25,262",Chile,"7,56,102",Chile,6435.0,Chile,12290.0,Chile,7801.0
26,China,0.0691,China,3210.0,China,1232.0,China,371.0,China,224.0,China,314.0,China,911.0,China,281.0,China,3500.0,China,33000.0,China,3800.0,China,3600.0,China,2650.0,China,777.0,China,2.0,China,74.0,China,36.0,China,52.0,China,"2,37,00,00,00,000",China,"15,98,00,00,00,000",China,507.0,China,"38,38,000",China,"1,35,00,000",China,"25,62,00,00,000",China,"75,28,55,402",China,"1,38,46,88,986",China,"95,96,961",China,14500.0,China,"1,10,000",China,22457.0
27,Colombia,0.6045,Colombia,469.0,Colombia,21.0,Colombia,38.0,Colombia,76.0,Colombia,80.0,Colombia,224.0,Colombia,0.0,Colombia,0.0,Colombia,595.0,Colombia,6.0,Colombia,110.0,Colombia,0.0,Colombia,453.0,Colombia,0.0,Colombia,11.0,Colombia,0.0,Colombia,4.0,Colombia,"10,60,00,00,000",Colombia,"1,24,60,00,00,000",Colombia,836.0,Colombia,"8,53,600",Colombia,"3,00,000",Colombia,"2,00,20,00,000",Colombia,"2,40,84,498",Colombia,"4,81,68,996",Colombia,"11,38,910",Colombia,3208.0,Colombia,24725.0,Colombia,6672.0
28,Croatia,1.0183,Croatia,78.0,Croatia,12.0,Croatia,0.0,Croatia,0.0,Croatia,27.0,Croatia,47.0,Croatia,0.0,Croatia,72.0,Croatia,604.0,Croatia,24.0,Croatia,151.0,Croatia,105.0,Croatia,28.0,Croatia,0.0,Croatia,0.0,Croatia,0.0,Croatia,0.0,Croatia,"80,00,00,000",Croatia,"48,10,00,00,000",Croatia,69.0,Croatia,14000.0,Croatia,82000.0,Croatia,"7,10,00,000",Croatia,"20,88,265",Croatia,"42,70,480",Croatia,56594.0,Croatia,5835.0,Croatia,785.0,Croatia,2237.0
29,Cuba,1.2208,Cuba,80.0,Cuba,38.0,Cuba,0.0,Cuba,2.0,Cuba,26.0,Cuba,14.0,Cuba,4.0,Cuba,1180.0,Cuba,670.0,Cuba,100.0,Cuba,150.0,Cuba,100.0,Cuba,12.0,Cuba,0.0,Cuba,0.0,Cuba,0.0,Cuba,2.0,Cuba,"50,00,00,000",Cuba,"30,06,00,00,000",Cuba,133.0,Cuba,50000.0,Cuba,"1,52,000",Cuba,"12,40,00,000",Cuba,"59,80,621",Cuba,"1,11,16,396",Cuba,"1,10,860",Cuba,3735.0,Cuba,240.0,Cuba,29.0
30,Czechia,0.5531,Czechia,95.0,Czechia,12.0,Czechia,16.0,Czechia,8.0,Czechia,15.0,Czechia,44.0,Czechia,15.0,Czechia,116.0,Czechia,682.0,Czechia,86.0,Czechia,85.0,Czechia,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Czechia,"2,96,90,00,000",Czechia,"2,05,20,00,00,000",Czechia,128.0,Czechia,2000.0,Czechia,"2,00,000",Czechia,"1,50,00,000",Czechia,"50,11,174",Czechia,"1,06,86,269",Czechia,78867.0,NaN,NaN,Czechia,664.0,Czechia,2046.0
31,Democratic Republic of the Congo,1.1389,Democratic Republic of the Congo,53.0,Democratic Republic of the Congo,2.0,Democratic Republic of the Congo,4.0,Democratic Republic of the Congo,13.0,Democratic Republic of the Congo,0.0,Democratic Republic of the Congo,34.0,Democratic Republic of the Congo,8.0,Democratic Republic of the Congo,175.0,Democratic Republic of the Congo,100.0,Democratic Republic of the Congo,16.0,Democratic Republic of the Congo,120.0,Democratic Republic of the Congo,57.0,Democratic Republic of the Congo,20.0,Democratic Republic of the Congo,0.0,Democratic Republic of the Congo,0.0,Democratic Republic of the Congo,0.0,Democratic Republic of the Congo,0.0,Democratic Republic of the Congo,"10,00,00,000",Democratic Republic of the Congo,"4,96,30,00,000",Democratic Republic of the Congo,198.0,Democratic Republic of the Congo,19160.0,Democratic Republic of the Congo,10500.0,Democratic Republic of the Congo,"18,00,00,000",Democratic Republic of the Congo,"3,41,12,410",Democratic Republic of the Congo,"8,52,81,024",Democratic Republic of the Congo,"23,44,858",Democratic Republic of the Congo,37.0,Democratic Republic of the Congo,15000.0,Democratic Republic of the Congo,10481.0
32,Denmark,0.7878,Denmark,113.0,Denmark,33.0,Denmark,0.0,Denmark,4.0,Denmark,38.0,Denmark,35.0,Denmark,0.0,Denmark,57.0,Denmark,972.0,Denmark,22.0,Denmark,0.0,Denmark,0.0,Denmark,74.0,Denmark,0.0,Denmark,0.0,Denmark,0.0,Denmark,9.0,Denmark,"4,76,00,00,000",Denmark,"4,84,80,00,00,000",Denmark,80.0,Denmark,"1,37,100",Denmark,"1,62,000",Denmark,"49,06,00,000",Denmark,"25,90,457",Denmark,"58,09,502",Denmark,43094.0,Denmark,7314.0,Denmark,400.0,Denmark,140.0
33,Dominican Republic,2.7504,Dominican Republic,49.0,Dominican Republic,0.0,Dominican Republic,8.0,Dominican Republic,10.0,Dominican Republic,4.0,Dominican Republic,28.0,Dominican Republic,0.0,Dominican Republic,6.0,Dominican Republic,20.0,Dominican Republic,0.0,Dominican Republic,20.0,Dominican Republic,0.0,Dominican Republic,33.0,Dominican Republic,0.0,Dominican Republic,0.0,Dominican Republic,0.0,Dominican Republic,0.0,Dominican Republic,"76,00,00,000",Dominican Republic,"29,16,00,00,000",Dominican Republic,36.0,Dominican Republic,0.0,Dominican Republic,"1,25,000",Dominican Republic,0.0,Dominican Republic,"48,19,818",Dominican Republic,"1,02,98,756",Dominican Republic,48320.0,Dominican Republic,1288.0,Dominican Republic,350.0,Dominican Republic,376.0
34,Ecuador,1.0062,Ecuador,108.0,Ecuador,9.0,Ecuador,0.0,Ecuador,22.0,Ecuador,29.0,Ecuador,50.0,Ecuador,0.0,Ecuador,232.0,Ecuador,413.0,Ecuador,15.0,Ecuador,102.0,Ecuador,26.0,Ecuador,19.0,Ecuador,0.0,Ecuador,2.0,Ecuador,0.0,Ecuador,2.0,Ecuador,"2,50,00,00,000",Ecuador,"39,29,00,00,000",Ecuador,432.0,Ecuador,"5,31,300",Ecuador,"2,82,000",Ecuador,"8,27,30,00,000",Ecuador,"76,96,551",Ecuador,"1,64,98,502",Ecuador,"2,83,560",Ecuador,2237.0,Ecuador,1500.0,Ecuador,2237.0
35,Egypt,0.1872,Egypt,1054.0,Egypt,215.0,Egypt,88.0,Egypt,59.0,Egypt,387.0,Egypt,294.0,Egypt,81.0,Egypt,4295.0,Egypt,11700.0,Egypt,1139.0,Egypt,2189.0,Egypt,1084.0,Egypt,316.0,Egypt,2.0,Egypt,8.0,Egypt,0.0,Egypt,7.0,Egypt,"11,20,00,00,000",Egypt,"77,47,00,00,000",Egypt,83.0,Egypt,"5,89,400",Egypt,"8,32,000",Egypt,"4,40,00,00,000",Egypt,"4,29,46,553",Egypt,"9,94,13,317",Egypt,"10,01,450",Egypt,2450.0,Egypt,3500.0,Egypt,2612.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 60 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Military Strength                        138 non-null    object
 1   Military Strength Power Index            138 non-null    float64
 2   Aircraft Strength                        138 non-null    object
 3   Aircraft Strength value                  138 non-null    float64
 4   Fighter/Interceptor Strength             138 non-null    object
 5   Fighter/Interceptor Strength value       138 non-null    float64
 6   Attack Aircraft Strength                 138 non-null    object
 7   Attack Aircraft Strength value           138 non-null    float64
 8   Transport Aircraft Fleet Strength        138 non-null    object
 9   Transport Aircraft Fleet Strength value  138 non-null    float64
 10  Trainer Aircraft Fleet                   138 non-null    object
 11  Trainer Aircraft Fleet value             138 non-null    float64
 12  Helicopter Fleet Strength                138 non-null    object
 13  Helicopter Fleet Strength value          138 non-null    float64
 14  Attack Helicopter Fleet Strength         138 non-null    object
 15  Attack Helicopter Fleet Strength value   138 non-null    float64
 16  Tank Strength                            138 non-null    object
 17  Tank Strength value                      138 non-null    float64
 18  AFV/APC Strength                         138 non-null    object
 19  AFV/APC Strength value                   138 non-null    float64
 20  Self-Propelled Artillery Strength        138 non-null    object
 21  Self-Propelled Artillery Strength value  138 non-null    float64
 22  Towed Artillery Strength                 138 non-null    object
 23  Towed Artillery Strength value           138 non-null    float64
 24  Rocket Projector Strength                138 non-null    object
 25  Rocket Projector Strength value          138 non-null    float64
 26  Navy Fleet Strengths                     124 non-null    object
 27  Navy Fleet Strengths value               124 non-null    float64
 28  Aircraft Carrier Fleet Strength          115 non-null    object
 29  Aircraft Carrier Fleet Strength value    115 non-null    float64
 30  Submarine Fleet Strength                 115 non-null    object
 31  Submarine Fleet Strength value           115 non-null    float64
 32  Destroyer Fleet Strength                 115 non-null    object
 33  Destroyer Fleet Strength value           115 non-null    float64
 34  Frigate Fleet Strength                   115 non-null    object
 35  Frigate Fleet Strength value             115 non-null    float64
 36  defense spending budget                  138 non-null    object
 37  defense spending budget value            138 non-null    object
 38  External Debt                            138 non-null    object
 39  External Debt value                      138 non-null    object
 40  Airport Totals                           138 non-null    object
 41  Airport Totals value                     138 non-null    float64
 42  Oil Production                           138 non-null    object
 43  Oil Production value                     138 non-null    object
 44  Oil Consumption                          138 non-null    object
 45  Oil Consumption value                    138 non-null    object
 46  Proven Oil Reserves                      138 non-null    object
 47  Proven Oil Reserves value                138 non-null    object
 48  Available Manpower                       138 non-null    object
 49  Available Manpower value                 138 non-null    object
 50  Total Population                         138 non-null    object
 51  Total Population value                   138 non-null    object
 52  Total Square Land Area                   138 non-null    object
 53  Total Square Land Area value             138 non-null    object
 54  Total Coastline Coverage                 109 non-null    object
 55  Total Coastline Coverage value           109 non-null    object
 56  Total Waterway Coverage                  138 non-null    object
 57  Total Waterway Coverage value            138 non-null    object
 58  Total Border Coverage                    129 non-null    object
 59  Total Border Coverage value              129 non-null    float64
dtypes: float64(20), object(40)
memory usage: 64.8+ KB

In [10]:
df.describe()

,Military Strength Power Index,Aircraft Strength value,Fighter/Interceptor Strength value,Attack Aircraft Strength value,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet value,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength value,Tank Strength value,AFV/APC Strength value,Self-Propelled Artillery Strength value,Towed Artillery Strength value,Rocket Projector Strength value,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength value,Destroyer Fleet Strength value,Frigate Fleet Strength value,Airport Totals value,Total Border Coverage value
count,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,124.000000,115.000000,115.000000,115.000000,115.000000,138.000000,129.000000
mean,1.460716,388.471014,81.565217,25.760870,30.231884,82.833333,154.065217,25.623188,646.565217,2485.695652,212.159420,393.978261,156.934783,84.983871,0.382609,4.800000,2.052174,3.521739,290.043478,3964.224806
std,1.324018,1231.981859,230.324777,94.528222,92.330436,240.803721,520.183631,97.326091,1515.463683,5410.546392,688.028987,805.781703,484.380984,146.114165,1.971653,13.706958,10.000740,6.481211,1212.967393,3760.099671
min,0.060600,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,29.000000
25%,0.574800,33.000000,0.000000,0.000000,3.000000,4.250000,15.250000,0.000000,19.250000,250.250000,0.000000,24.250000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,33.500000,1587.000000
50%,1.034100,111.000000,17.000000,0.000000,9.000000,26.000000,44.000000,2.000000,153.000000,734.500000,23.000000,108.000000,24.000000,38.000000,0.000000,0.000000,0.000000,0.000000,68.000000,2816.000000
75%,2.021525,290.250000,60.500000,15.750000,26.000000,79.250000,126.750000,17.750000,436.250000,2000.000000,97.250000,296.500000,99.750000,77.750000,0.000000,4.000000,0.000000,5.500000,150.750000,5267.000000
max,10.168100,13264.000000,2085.000000,742.000000,945.000000,2643.000000,5768.000000,967.000000,12950.000000,39253.000000,6083.000000,4465.000000,3860.000000,984.000000,20.000000,83.000000,91.000000,52.000000,13513.000000,22457.000000

## Implement basic steps to see how is your data looks like

## Convert multi index columns to one level

## Detect and drop duplicated columns

## Check for missing values

## Deal with missing values 
* Hint-1, use wikipedia to fill in missing values ​​comparing with similar countries
* Hint-2, Georeferences of countries can help you

## Fix the dtypes

## Drop the features that not affect military power
* Hint-1,  Georeferences not proper features

## Visualy inspect the some features

## Decriptive statistics

# Data Preprocessing

# Modelling

## Hopkins Test 
#### Assess the clusterability of a dataset. A score between 0 and 1, a score around 0.5 express no clusterability, a score tending to 1 express an uniform distrubution so clustering can't be useful and  0 express  not an uniform distrubution hence clusterering can be useful.

## Clustering with K-means

### Elbow Method 
### We use this method to find optimal k value by looking up to break point of graph.

### Model Building and label visualisation

### Evaluate

## Hierarchical Clustering

### Dendogram

### Model Building and label visualisation

### Evaluate